version: "3.8"
services:
  hub:
    image: selenium/hub
    container_name: myHUB
    ports:
      - "4444:4444"
    networks:
      - my_network

  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - my_network
    deploy:
      replicas: 5

  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - my_network
    deploy:
      replicas: 5

networks:
  my_network:
    name: grid